name: 🐞 Bug
description: Report an issue with the script
title: "[BUG] <title>"
labels: ["Bug", "Needs Triage"]
body:
- type: checkboxes
  attributes:
    label: Are you sure this is a new issue?
    description: Please check that this issue is not mentioned in the README and that an issue doesn't exist already for this bug.
    options:
    - label: I have read the usage instructions
      required: true
    - label: I have read the FAQ
      required: true
    - label: I have searched for existing issues
      required: true
- type: input
  attributes:
    label: Operating System
    description: What OS and OS version are you using?
    placeholder: "Ubuntu 20.04"
    required: true
- type: input
  attributes:
    label: Browser
    description: What browser and browser version are you using?
    placeholder: "Chrome 131"
    required: true
- type: textarea
  attributes:
    label: What is the issue?
    description: |
      Please include the following details:
        - A description of the issue you're experiencing
        - Steps to reproduce the issue
        - A log file or screenshot of the console so I can see what is happening. You can save a log of the devtools console by right-clicking anywhere and choosing "Save as...".

      > [!TIP]
      > You can attach files by clicking this area to highlight it and then dragging files in.
  validations:
    required: true
