name: 🐛 Bug
description: Report an issue with the project
title: "🐛 <title>"
labels: ["🐛 bug", "⏰ new"]
body:
- type: checkboxes
  attributes:
    label: Are you sure this is a new bug?
    description: Please check that this bug is not mentioned in the README and that an issue doesn't exist already for it.
    options:
    - label: I have read the usage instructions
      required: true
    - label: I have read the FAQ
      required: true
    - label: I have searched for existing issues
      required: true
- type: input
  attributes:
    label: Operating System
    description: What OS and OS version are you using?
    placeholder: "Ubuntu 22.04"
  validations:
    required: true
- type: input
  attributes:
    label: Browser
    description: What browser and browser version are you using?
    placeholder: "Chrome 133"
  validations:
    required: true
- type: textarea
  attributes:
    label: Bug description
    description: Describe the bug you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    description: Give steps to reproduce the behavior.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true
- type: textarea
  attributes:
    label: Add a log file or screenshot of the output or error messages you're seeing.
    description: |
      Please include a log file or screenshot of the issue.

      > [!TIP]
      > You can attach files by clicking this area to highlight it and then dragging files in.
  validations:
    required: true
